MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "output_dir/pretrained/X-152-COCO-for-icdar.pth"
  BACKBONE:
    CONV_BODY: "R-152-FPN"
    OUT_CHANNELS: 256
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  MASKIOU_ON: True
INPUT:
  MIN_SIZE_TRAIN: (400, 800, 1200)
DATASETS:
  TRAIN: ("icdar_lsvt_train_cocostyle",)
  TEST: ("icdar_lsvt_val_cocostyle",)
DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
SOLVER:
  MAX_ITER: 20000
  BASE_LR: 0.002
  STEPS: (15000, )
TEST:
  IMS_PER_BATCH: 16
OUTPUT_DIR: 'output_dir/caffe2/e2e_ms_rcnn_X-152-32x8d-FPN-IN5k_1.44x_caffe2_lsvt_scale3'
